# WARNING - Generated by {fusen} from /dev/flat_appli_format.Rmd: do not edit by hand

#' Ouvrir l'application Shiny d'édition du tableur
#' 
#' Cette fonction permet d'ouvrir l'interface graphique s'appuyant 
#' sur les fonctions de formatage du package pour éditer des tableaux plus rapidement
#' 
#' @return Rien n'est renvoyé, l'appli s'ouvre.
#' 
#' @importFrom shiny runApp
#' @importFrom shiny shinyAppDir
#' @importFrom shiny fileInput
#' @importFrom shiny shinyApp
#' @importFrom shiny tags
#' @importFrom shiny checkboxInput
#' @importFrom shiny radioButtons
#' @importFrom shiny textInput
#' @importFrom shiny tableOutput
#' @importFrom shiny uiOutput
#' @importFrom shiny verbatimTextOutput
#' @importFrom shiny actionButton
#' @importFrom shiny req
#' @importFrom shiny renderUI
#' @importFrom shiny renderPrint
#' @importFrom shiny selectInput
#' @importFrom shiny observeEvent
#' @importFrom shiny showModal
#' @importFrom shiny removeModal
#' @importFrom shiny p
#' @importFrom shiny div
#' @importFrom shiny fluidRow
#' @importFrom shiny column
#' @importFrom shiny tabPanel
#' @importFrom shiny downloadButton
#' @importFrom shiny downloadHandler
#' @importFrom shiny icon
#' @importFrom shinycssloaders withSpinner
#' @importFrom shinyalert shinyalert
#' @importFrom shinyWidgets prettyRadioButtons
#' @importFrom shinyWidgets actionBttn
#' @importFrom shinyWidgets downloadBttn
#' @importFrom bs4Dash dashboardPage
#' @importFrom bs4Dash dashboardHeader
#' @importFrom bs4Dash dashboardSidebar
#' @importFrom bs4Dash dashboardFooter
#' @importFrom bs4Dash dashboardBody
#' @importFrom bs4Dash bs4DashControlbar
#' @importFrom bs4Dash tabBox
#' @importFrom bs4Dash sidebarMenu
#' @importFrom bs4Dash menuItem
#' @importFrom bs4Dash tabItems
#' @importFrom bs4Dash tabItem
#' @importFrom bs4Dash updateTabItems
#' @importFrom bs4Dash skinSelector
#' @importFrom magrittr %>%
#' @importFrom openxlsx write.xlsx
#' @importFrom purrr map
#' @importFrom purrr set_names
#' @importFrom purrr %>%
#' @importFrom stringr str_replace
#' @importFrom stringr str_trim
#' @importFrom rstudioapi selectFile
#' @importFrom rstudioapi selectDirectory
#' @importFrom DT datatable
#' @importFrom DT DTOutput
#' @importFrom DT renderDataTable
#' @importFrom DT selectRows
#' @importFrom DT selectCells
#' @importFrom DT dataTableProxy
#' 
#' @export
#' 
#' @examples
#' library(agreste)
#' \dontrun{
#' app_formatage()
#' }
app_formatage <- function() {
  
  wb <- createWorkbook()
  list_sheets_with_note <- c(" ")
  list_col_data_types <- list()
  index_current_sheet <- 0
  datapath <- getwd()
  count_tabs <- c()
  ordre <- c()
  
  plan <- agreste::modele_plan[NULL,]
  
  wd <- getwd()
  
  ui = dashboardPage(
    title = "Mise en forme de tableaux",
    dark = NULL,
    scrollToTop = TRUE,
    header = dashboardHeader(title = "Mise en forme de tableaux",
                             div(style = "position:relative; left:calc(80%);",
                                 actionBttn("close", "Fermer",
                                            color = "danger",
                                            icon = icon("door-open")))
                             ),
                                          
    
    sidebar = dashboardSidebar(
      minified = FALSE,
      sidebarMenu(id = "tabs",
                  menuItem("Vue d'ensemble",
                           tabName = "overview",
                           icon = icon("globe")),
                menuItem('Import de fichiers',
                         tabName = 'import',
                         icon = icon('upload')),
                menuItem("Paramètres d'import",
                         tabName = 'import_param',
                         icon = icon('bars')),
                menuItem('Ordre des tableaux',
                         tabName = 'table_order',
                         icon = icon('sort')),
                menuItem('Format des tableaux',
                         tabName = 'table_format',
                         icon = icon('table')),
                menuItem('Enregistrement',
                         tabName = 'sauvegarde',
                         icon = icon('download'))
      
        )
      ),
    controlbar = bs4DashControlbar(
      skin = "light",
      width = 350,
       div(style = "position:relative; left:calc(10%);",
           skinSelector())
    ),
    footer = dashboardFooter(
      fluidRow(
        column(11,
               actionBttn(inputId = "Previous", label = icon("arrow-left"))),
        column(1,
               actionBttn(inputId = "Next", label = icon("arrow-right")))
      )
    ),
    body = dashboardBody(
      
      tabItems(
        tabItem(
          tabName = "overview",
          tags$h4("Aide à la création des tableaux associés aux publications."),
          tags$h5("Veuillez lire attentivement ces instructions avant de débuter :"),
          div(class = "card-deck",
              div(class = "card text-white bg-primary mb-3", style = "max-width: 18rem;",
              div(class = "card-header", tags$h4("Import")),
              div(class = "card-body",
                  div(class = "card-title", "Fichiers à importer :"),
                  div(class = "card-text",
                      tags$ul(
                        tags$li("Fichier de plan si nécessaire"),
                        tags$li("Tableaux de données à formater"),
                        tags$li("Sélection du dossier où sont stockées les tableaux")
                      ))),
                div(class = "card-footer", icon("exclamation-triangle", verify_fa = FALSE),
                    " Si vous importez un fichier de plan, il est nécessaire de l'importer avant les tableaux.")),
              div(class = "card text-white bg-secondary mb-3", style = "max-width: 18rem;",
                  div(class = "card-header", tags$h4("Paramètres d'import")),
                  div(class = "card-body",
                      div(class = "card-text",
                          tags$ul(
                            tags$li("Séparateur de colonnes"),
                            tags$li("Séparateur décimal"),
                            tags$li("Type de publication")
                          ))
                      )
                  ),
              div(class = "card text-white bg-info mb-3", style = "max-width: 18rem;",
                  div(class = "card-header", tags$h4("Ordre des tableaux")),
                  div(class = "card-body",
                      div(class = "card-text",
                          "Choix de l'ordre dans lequel vous souhaitez que vos tableaux apparaissent dans le fichier Excel formaté.")
                      )
                  ),
              div(class = "card text-white bg-dark mb-3", style = "max-width: 18rem;",
                  div(class = "card-header", tags$h4("Formatage")),
                  div(class = "card-body",
                      div(class = "card-text",
                          "Parcourez vos différents tableaux et définissez les différents paramètres d'apparence de chacun (par exemple taille des colonnes, unités, source, cellules à fusionner...)")
                      ),
                  div(class = "card-footer", icon("exclamation-triangle", verify_fa = FALSE),
                      " Si vous n'avez pas importé de plan, vous devez valider pour chaque tableau les colonnes et les unités")
                  ),
              div(class = "card text-white bg-success mb-3", style = "max-width: 18rem;",
                  div(class = "card-header", tags$h4("Enregistrement")),
                  div(class = "card-body",
                      div(class = "card-text",
                          tags$ul(
                            tags$li("Exporter le plan créé (pour réutilisation)"),
                            tags$li("Export du fichier Excel formaté")
                          )
                      )
                  )))
        ),
        tabItem(
          tabName = "import",
          div(style="display: inline-block;vertical-align:top; width: 500px;",
              tags$p(
                "Vous devez impérativement importer vos fichiers de données, et sélectionner le dossier qui les contient pour que le formatage fonctionne. Si vous ne choisissez pas de dossier, votre répertoire de travail actuel sera utilisé."
              ),
              tags$p(
                "Si vous avez déjà créé un plan auparavant, vous pouvez l'importer afin de le modifier."
              )),
          div(style="display: inline-block;vertical-align:top; width: 500px;",
              fileInput(inputId = "upload_plan",
                label = "Importer un plan",
                multiple = FALSE,
                accept = ".xlsx"),
            fileInput(
              inputId = "upload",
              label = "Choisir les fichiers",
              multiple = TRUE,
              accept = c("text/csv",
                         "text/comma-separated-values,text/plain",
                         ".csv",
                         ".xlsx",
                         ".rds",
                         ".Rds",
                         ".parquet",
                         ".xls",
                         ".ods")),
            actionBttn(inputId = "datadir", label = "Dossier de données", icon = icon("folder"), color = "royal"),
            verbatimTextOutput(outputId = "dirpath"))
        ),
        tabItem(tabName = "import_param",
                div(style="display: inline-block;vertical-align:top; width: 500px;",
                    radioButtons("sep", "Separateur",
                       choices = c(Virgule = ",",
                                   "Point Virgule" = ";",
                                   Tab = "\t"),
                       selected = ","),
                tags$hr(),
                radioButtons("virg", "Séparateur décimal",
                             choices = c(Virgule = ",",
                                         Point = "."),
                             selected = ",")),
                div(style="display: inline-block;vertical-align:top; width: 500px;",
                    prettyRadioButtons(inputId = "format",
                                       label = "Type de publication",
                                       choices = c("Chiffres et données" = "chiffres_et_donnees",
                                                   Primeur = "primeur"),
                                       selected = "chiffres_et_donnees"),
                    checkboxInput(
                      inputId = "largeur_max",
                      label = "Utiliser la règle de diffusion de largeur maximale des tableaux (actuellement 83)",
                      value = TRUE
                    )
                  )),
        tabItem(tabName = "table_order",
                p("Sélectionnez tous les fichiers dans l'ordre que vous souhaitez pour le modifier :"),
                DTOutput("files_order"),
                verbatimTextOutput("liste_ordre"),
                actionBttn("validate_order", "Valider", color = "success",
                           icon = icon("check"))),
        tabItem(tabName = "table_format",
                DTOutput("files"),
                DTOutput("contents") %>% withSpinner(),
                tabBox(
                  width = 12,
                  tabPanel(
                    title = "Paramètres",
                    tabBox(
                  tabPanel(title = "Titres",
                           id = "tab_titles",
                           textInput("feuille", "Nom de la feuille :"),
                           textInput("titre_primeur", "Titre du document (si primeur)"),
                           textInput("title", "Titre du tableau :")),
                  tabPanel(title = "Colonnes",
                           id = "tab_cols",
                           uiOutput("deroul"),
                           uiOutput("larg"),
                           actionBttn("validate_colonnes", "Valider", color = "success",
                                      icon = icon("check"))),
                  tabPanel(title = "Lignes",
                           id = "tab_lines",
                           p("Séléctionnez les lignes souhaitées puis cliquez sur le bouton pour les formater :"),
                           div(style="display: inline-block;vertical-align:top; width: 100px;",
                               actionButton("lignes_titre", "Lignes de surtitre")),
                           div(style="display: inline-block;vertical-align:top; width: 100px;",
                               actionButton("lignes_section", "Lignes de section")),
                           div(style="display: inline-block;vertical-align:top; width: 100px;",
                               actionButton("lignes_precision_1", "Lignes de précision 1")),
                           div(style="display: inline-block;vertical-align:top; width: 100px;",
                               actionButton("lignes_precision_2", "Lignes de précision 2")),
                           div(style="display: inline-block;vertical-align:top; width: 100px;",
                               actionButton("lignes_precision_3", "Lignes de précision 3")),
                           div(style="display: inline-block;vertical-align:top; width: 100px;",
                               actionButton("lignes_precision_4", "Lignes de précision 4")),
                           div(style="display: inline-block;vertical-align:top; width: 100px;",
                               actionButton("lignes_sous_total", "Lignes de sous-total")),
                           div(style="display: inline-block;vertical-align:top; width: 100px;",
                               actionButton("lignes_total", "Lignes de total")),
                           div(style="display: inline-block;vertical-align:top; width: 100px;",
                               actionButton("lignes_italique", "Lignes en italique")),
                           tags$hr(),
                           div(style="display: inline-block;vertical-align:top; width: 100px;",
                               verbatimTextOutput("disp_lignes_titre")),
                           div(style="display: inline-block;vertical-align:top; width: 100px;",
                               verbatimTextOutput("disp_lignes_section")),
                           div(style="display: inline-block;vertical-align:top; width: 100px;",
                               verbatimTextOutput("disp_lignes_precision_1")),
                           div(style="display: inline-block;vertical-align:top; width: 100px;",
                               verbatimTextOutput("disp_lignes_precision_2")),
                           div(style="display: inline-block;vertical-align:top; width: 100px;",
                               verbatimTextOutput("disp_lignes_precision_3")),
                           div(style="display: inline-block;vertical-align:top; width: 100px;",
                               verbatimTextOutput("disp_lignes_precision_4")),
                           div(style="display: inline-block;vertical-align:top; width: 100px;",
                               verbatimTextOutput("disp_lignes_sous_total")),
                           div(style="display: inline-block;vertical-align:top; width: 100px;",
                               verbatimTextOutput("disp_lignes_total")),
                           div(style="display: inline-block;vertical-align:top; width: 100px;",
                               verbatimTextOutput("disp_lignes_italique"))),
                  tabPanel(title = "Unités",
                           id = "tab_units",
                           radioButtons(inputId = "is_unite_unif",
                                        label = "L'unité est commune à toutes les colonnes :",
                                        choices = c("Oui" = "oui",
                                                    "Non" = "non"),
                                        selected = "oui"),
                           p("(remplir uniquement la première si oui)"),
                           uiOutput("unites"),
                           actionBttn("validate_unites", "Valider", color = "success",
                                      icon = icon("check"))),
                  tabPanel(title = "Textes",
                           id = "tab_text",
                           tags$h5("Lecture :"),
                           div(style="display: inline-block;vertical-align:top; width: 300px;",
                               textInput("note", "Note de lecture :")),
                           div(style="display: inline-block;vertical-align:top; width: 300px;",
                               textInput("source", "Source")),
                           div(style="display: inline-block;vertical-align:top; width: 300px;",
                               textInput("champ", "Champ")),
                           tags$br(),
                           tags$h5("Sommaire :"),
                           p("Laissez les champs vides si identiques au tableau précédent"),
                           div(style="display: inline-block;vertical-align:top; width: 300px;",
                               textInput("chapitre", "Nom du chapitre :")),
                           div(style="display: inline-block;vertical-align:top; width: 300px;",
                               textInput("sous_chapitre", "Nom du sous-chapitre :"))),
                  width = 12, 
                  height = 500,
                  collapsed = FALSE,
                  id = "setting_box"
                )),
                  tabPanel(
                    title = "Cellules à fusionner",
                    DTOutput("contents_fusion"),
                    verbatimTextOutput("liste_fusion"),
                    actionBttn("add_fusion", "Fusionner",
                               color = "royal", icon = icon("plus")),
                    actionBttn("delete_last_merge", "Annuler la dernière fusion",
                               color = "warning", icon = icon("trash"))
                  )
                )
                ),
        tabItem(tabName = "sauvegarde",
                downloadBttn("exporter", "Exporter le plan"),
                downloadBttn("enreg", "Enregistrer les tableaux formatés"))
      )
    )
  )
  
  server = function(input, output, session) {
    
    options(shiny.maxRequestSize=15*1024^2) # set maximum file size to 15MB
    
    observeEvent(input$upload, {
      ordre <<- 1:nrow(input$upload)
      if (length(input$upload_plan) == 0) {
        plan <<- fill_plan(plan = agreste::modele_plan[NULL,], input = input)
      }
    })
    
    observeEvent(input$upload_plan, {
      inFile <- input$upload_plan
      if (is.null(inFile)) {
        return(NULL)
      }
      plan <<- read.xlsx(xlsxFile = inFile$datapath, sheet = 1, colNames = TRUE)
      plan[is.na(plan)] <<- ""
      count_tabs <<- c()
    }, ignoreNULL = TRUE)
    
    output$files <- renderDataTable({
      req(input$upload)
      datatable(input$upload,
                selection = list(mode = "single", selected = 1),
                options = list(pageLength = 100,
                               lengthMenu = c(5,10,20,50,100)))
    })
    
    output$files_order <- renderDataTable({
      req(input$upload)
      datatable(input$upload,
                selection = list(mode = "multiple"),
                options = list(pageLength = 100,
                               lengthMenu = c(5,10,20,50,100)))
    })
    
    observeEvent(input$datadir, {
      dpath <- selectDirectory(caption = "Dossier contenant les données", label = "Sélectionner")
      if (!is.null(dpath)) {
        output$dirpath <- renderPrint(datapath)
        datapath <<- dpath
      } else {
        output$dirpath <- renderPrint(datapath)
      }

    }, ignoreNULL = TRUE)

    all_files <- reactive({
      req(input$upload)
      partial <- function(f, ...) {
        l <- list(...)
        function(...) {
          do.call(f, c(l, list(...)))
        }
      }
      default_arg_func <- partial(read_any_file,
                                  header = TRUE,
                                  sep = input$sep,
                                  decimal_mark = input$virg,
                                  sheet = 1)
      map(input$upload$datapath, default_arg_func) %>%
        set_names(input$upload$name)
    })
    
    output$contents <- renderDataTable(
      options = list(pageLength = 200,
                     lengthMenu = c(5,15,50,100,200)),
      expr = {
      
      req(input$upload)
      req(all_files())
      req(input$files_rows_selected)
      
      all_files()[[
        input$upload$name[[ordre[input$files_rows_selected]]]
      ]]
      
    })
    
    output$contents_fusion <- renderDataTable(selection = list(target = 'cell'),
                                              options = list(pageLength = 200,
                                                             lengthMenu = c(5,15,50,100,200)),
                                              expr = {
      
      req(input$upload)
      req(all_files())
      req(input$files_rows_selected)
      
      df <- all_files()[[
              input$upload$name[[ordre[input$files_rows_selected]]]
            ]] %>% as.data.frame()
      cols <- names(df)
      names(df) <- NULL
      df[seq(2,nrow(df)+1),] <- 
        df[seq(1,nrow(df)),]
      df[1,] <- as.list(cols)
      df
    })
    
    output$disp_lignes_titre <- renderPrint(plan$Lignes_titre[input$files_rows_selected])
    output$disp_lignes_section <- renderPrint(plan$Lignes_section[input$files_rows_selected])
    output$disp_lignes_precision_1 <- renderPrint(plan$Lignes_precision_1[input$files_rows_selected])
    output$disp_lignes_precision_2 <- renderPrint(plan$Lignes_precision_2[input$files_rows_selected])
    output$disp_lignes_precision_3 <- renderPrint(plan$Lignes_precision_3[input$files_rows_selected])
    output$disp_lignes_precision_4 <- renderPrint(plan$Lignes_precision_4[input$files_rows_selected])
    output$disp_lignes_sous_total <- renderPrint(plan$Lignes_sous_total[input$files_rows_selected])
    output$disp_lignes_total <- renderPrint(plan$Lignes_total[input$files_rows_selected])
    output$disp_lignes_italique <- renderPrint(plan$Lignes_italique[input$files_rows_selected])
    output$liste_fusion <- renderPrint(plan$Cellules_a_fusionner[input$files_rows_selected])
    
    global <- reactiveValues(tab_id = "")
    tab_id <- c('overview', 'import','import_param','table_order','table_format','sauvegarde')
    
    Current <- reactiveValues(
      Tab = "overview"
    )
    
    observeEvent(
      input[["tabs"]],
      {
        Current$Tab <- input[["tabs"]]
      }
    )
    
    observeEvent(
      input[["Previous"]],
      {
        tab_id_position <- match(Current$Tab, tab_id) - 1
        if (isTRUE(tab_id_position == 0)) tab_id_position <- length(tab_id)
        Current$Tab <- tab_id[tab_id_position]
        updateTabItems(session, "tabs", tab_id[tab_id_position]) 
      }
    )
    
    observeEvent(
      input[["Next"]],
      {
        tab_id_position <- match(Current$Tab, tab_id) + 1
        if (isTRUE(tab_id_position > length(tab_id))) tab_id_position <- 1
        Current$Tab <- tab_id[tab_id_position]
        updateTabItems(session, "tabs", tab_id[tab_id_position]) 
      }
    )
    
    output$deroul <- renderUI({
          req(input$upload)
          req(all_files())
          req(input$files_rows_selected)
          
          df <- all_files()[[
            input$upload$name[[ordre[input$files_rows_selected]]]
          ]]
          
          if (!is.null(input$upload_plan) & table(count_tabs)[input$files_rows_selected] < 1) {
            plan <<- read.xlsx(xlsxFile = input$upload_plan$datapath, sheet = 1, colNames = TRUE)
            plan[is.na(plan)] <<- ""
          }
          liste_data_types <- c()
          if (plan$Type_colonnes[input$files_rows_selected] == "") {
            for (colonne in df) {
              to_add <- switch (class(colonne),
                "character" = "texte",
                "numeric" = "decimal",
                "integer" = "numerique"
              )
              liste_data_types <- append(liste_data_types, to_add)
            }
            
          } else {
            liste_data_types <- unlist(strsplit(plan$Type_colonnes[input$files_rows_selected], split = ", "))
          }
          
          
          lapply(1:ncol(df), function(i) {
            div(style="display: inline-block;vertical-align:top; width: 100px;",
                selectInput(inputId = paste("col_",
                                            as.character(i),
                                            sep = ""),
                            label = paste("Colonne",
                                          as.character(i),
                                          sep = " "),
                            choices = c("Texte" = "texte",
                                        "Entier" = "numerique",
                                        "Décimal" = "decimal"),
                            selected = liste_data_types[i]))
            })
          })
        
    
      
    output$larg <- renderUI({
      req(input$upload)
      req(all_files())
      req(input$files_rows_selected)
      
      df <- all_files()[[
        input$upload$name[[ordre[input$files_rows_selected]]]
      ]]
      
      if (!is.null(input$upload_plan) & table(count_tabs)[input$files_rows_selected] < 1) {
        plan <<- read.xlsx(xlsxFile = input$upload_plan$datapath, sheet = 1, colNames = TRUE)
        plan[is.na(plan)] <<- ""
      }
      
      if (plan$Taille_colonnes[input$files_rows_selected] == "" | plan$Taille_colonnes[input$files_rows_selected] == "auto" | substr(plan$Taille_colonnes[input$files_rows_selected], 1, 1) == "0") {
        liste_col_widths <- rep(round(83/ncol(df), digits = 2) - 0.01, ncol(df))
      } else {
        liste_col_widths <- as.numeric(unlist(strsplit(str_trim(plan$Taille_colonnes[input$files_rows_selected]), split = ", ")))
      }
      
      lapply(1:ncol(df), function(i) {
        div(style="display: inline-block;vertical-align:top; width: 100px;",
            numericInput(inputId = paste("taille_",
                                        as.character(i),
                                        sep = ""),
                      label = paste("Largeur",
                                      as.character(i),
                                      sep = " "),
                      value = liste_col_widths[i],
                      min = 3,
                      max = 83,
                      step = 0.01))
      })
    })
    
    output$unites <- renderUI({
      req(input$upload)
      req(all_files())
      req(input$files_rows_selected)
      
      df <- all_files()[[
        input$upload$name[[ordre[input$files_rows_selected]]]
      ]]
      
      if (!is.null(input$upload_plan) & table(count_tabs)[input$files_rows_selected] < 1) {
        plan <<- read.xlsx(xlsxFile = input$upload_plan$datapath, sheet = 1, colNames = TRUE)
        plan[is.na(plan)] <<- ""
      }
      
      if (plan$Liste_unites[input$files_rows_selected] == "") {
        liste_unites <- c("unité", rep("", ncol(df) - 1))
      } else {
        liste_unites <- unlist(strsplit(plan$Liste_unites[input$files_rows_selected], split = ", "))
      }
      
      lapply(1:ncol(df), function(i) {
        div(style="display: inline-block;vertical-align:top; width: 100px;",
            textInput(inputId = paste("unite_",
                                        as.character(i),
                                        sep = ""),
                      label = paste("Unité",
                                      as.character(i),
                                      sep = " "),
                      value = liste_unites[i]))
      })
    })
    
    observeEvent(input$close, {
      stopApp()
    })
    
    observeEvent(c(input$files_rows_selected, input$upload_plan), {
      updateTabsetPanel(inputId = "setting_box", selected = "Titres")
      req(input$upload)
      req(input$files_rows_selected)
      updateTextInput(inputId = "feuille", value = plan$Nom_feuille[input$files_rows_selected])
      updateTextInput(inputId = "titre_primeur", value = plan$Titre_document[1])
      updateTextInput(inputId = "title", value = plan$Titre[input$files_rows_selected])
      updateTextInput(inputId = "note", value = plan$Note_de_lecture[input$files_rows_selected])
      updateTextInput(inputId = "source", value = plan$Source[input$files_rows_selected])
      updateTextInput(inputId = "champ", value = plan$Champ[input$files_rows_selected])
      updateTextInput(inputId = "chapitre", value = plan$Chapitre[input$files_rows_selected])
      updateTextInput(inputId = "sous_chapitre", value = plan$`Sous-chapitre`[input$files_rows_selected])
      count_tabs <<- c(count_tabs, input$files_rows_selected)
    })
    
    output$exporter <- downloadHandler(
      filename = function() {
        "plan.xlsx"
      },
      content = function(file) {
        write.xlsx(x = plan, file = file, overwrite = TRUE,
                   rowNames = FALSE, colNames = TRUE)
      
      }
    )
    
    observeEvent(input$lignes_titre, {
      req(input$files_rows_selected)
      lignes <- input$contents_rows_selected
      tab_index <- input$files_rows_selected
      plan_modif <- plan
      plan_modif$Lignes_titre[tab_index] <- paste(c("1", lignes + 1), collapse = ", ")
      plan <<- plan_modif
      output$disp_lignes_titre <- renderPrint(plan$Lignes_titre[input$files_rows_selected])
      selectRows(proxy_contents, NULL)
    })
    
    observeEvent(input$lignes_section, {
      req(input$files_rows_selected)
      lignes <- input$contents_rows_selected
      tab_index <- input$files_rows_selected
      plan_modif <- plan
      plan_modif$Lignes_section[tab_index] <- paste(lignes, collapse = ", ")
      plan <<- plan_modif
      output$disp_lignes_section <- renderPrint(plan$Lignes_section[input$files_rows_selected])
      selectRows(proxy_contents, NULL)
    })
    
    observeEvent(input$lignes_precision_1, {
      req(input$files_rows_selected)
      lignes <- input$contents_rows_selected
      tab_index <- input$files_rows_selected
      plan_modif <- plan
      plan_modif$Lignes_precision_1[tab_index] <- paste(lignes, collapse = ", ")
      plan <<- plan_modif
      output$disp_lignes_precision_1 <- renderPrint(plan$Lignes_precision_1[input$files_rows_selected])
      selectRows(proxy_contents, NULL)
    })
    
    observeEvent(input$lignes_precision_2, {
      req(input$files_rows_selected)
      lignes <- input$contents_rows_selected
      tab_index <- input$files_rows_selected
      plan_modif <- plan
      plan_modif$Lignes_precision_2[tab_index] <- paste(lignes, collapse = ", ")
      plan <<- plan_modif
      output$disp_lignes_precision_2 <- renderPrint(plan$Lignes_precision_2[input$files_rows_selected])
      selectRows(proxy_contents, NULL)
    })
    
    observeEvent(input$lignes_precision_3, {
      req(input$files_rows_selected)
      lignes <- input$contents_rows_selected
      tab_index <- input$files_rows_selected
      plan_modif <- plan
      plan_modif$Lignes_precision_3[tab_index] <- paste(lignes, collapse = ", ")
      plan <<- plan_modif
      output$disp_lignes_precision_3 <- renderPrint(plan$Lignes_precision_3[input$files_rows_selected])
      selectRows(proxy_contents, NULL)
    })
    
    observeEvent(input$lignes_precision_4, {
      req(input$files_rows_selected)
      lignes <- input$contents_rows_selected
      tab_index <- input$files_rows_selected
      plan_modif <- plan
      plan_modif$Lignes_precision_4[tab_index] <- paste(lignes, collapse = ", ")
      plan <<- plan_modif
      output$disp_lignes_precision_4 <- renderPrint(plan$Lignes_precision_4[input$files_rows_selected])
      selectRows(proxy_contents, NULL)
    })
    
    observeEvent(input$lignes_sous_total, {
      req(input$files_rows_selected)
      lignes <- input$contents_rows_selected
      tab_index <- input$files_rows_selected
      plan_modif <- plan
      plan_modif$Lignes_sous_total[tab_index] <- paste(lignes, collapse = ", ")
      plan <<- plan_modif
      output$disp_lignes_sous_total <- renderPrint(plan$Lignes_sous_total[input$files_rows_selected])
      selectRows(proxy_contents, NULL)
    })
    
    observeEvent(input$lignes_total, {
      req(input$files_rows_selected)
      lignes <- input$contents_rows_selected
      tab_index <- input$files_rows_selected
      plan_modif <- plan
      plan_modif$Lignes_total[tab_index] <- paste(lignes, collapse = ", ")
      plan <<- plan_modif
      output$disp_lignes_total <- renderPrint(plan$Lignes_total[input$files_rows_selected])
      selectRows(proxy_contents, NULL)
    })
    
    observeEvent(input$lignes_italique, {
      req(input$files_rows_selected)
      lignes <- input$contents_rows_selected
      tab_index <- input$files_rows_selected
      plan_modif <- plan
      plan_modif$Lignes_italique[tab_index] <- paste(lignes, collapse = ", ")
      plan <<- plan_modif
      output$disp_lignes_italique <- renderPrint(plan$Lignes_italique[input$files_rows_selected])
      selectRows(proxy_contents, NULL)
    })
    
    observeEvent(input$feuille, {
      req(input$upload)
      req(all_files())
      req(input$files_rows_selected)
      
      df <- all_files()[[
        input$upload$name[[ordre[input$files_rows_selected]]]
      ]]
      plan <<- valider_donnees(plan = plan, input = input, df = df, a_modifier = "feuille")
    })
    
    observeEvent(input$titre_primeur, {
      req(input$upload)
      req(all_files())
      req(input$files_rows_selected)
      
      df <- all_files()[[
        input$upload$name[[ordre[input$files_rows_selected]]]
      ]]
      plan <<- valider_donnees(plan = plan, input = input, df = df, a_modifier = "titre_primeur")
    })
    
    observeEvent(input$title, {
      req(input$upload)
      req(all_files())
      req(input$files_rows_selected)
      
      df <- all_files()[[
        input$upload$name[[ordre[input$files_rows_selected]]]
      ]]
      plan <<- valider_donnees(plan = plan, input = input, df = df, a_modifier = "titre")
    })
    
    
    observeEvent(input$note, {
      req(input$upload)
      req(all_files())
      req(input$files_rows_selected)
      
      df <- all_files()[[
        input$upload$name[[ordre[input$files_rows_selected]]]
      ]]
      plan <<- valider_donnees(plan = plan, input = input, df = df, a_modifier = "note")
    })
    
    observeEvent(input$source, {
      req(input$upload)
      req(all_files())
      req(input$files_rows_selected)
      
      df <- all_files()[[
        input$upload$name[[ordre[input$files_rows_selected]]]
      ]]
      plan <<- valider_donnees(plan = plan, input = input, df = df, a_modifier = "source")
    })
    
    observeEvent(input$champ, {
      req(input$upload)
      req(all_files())
      req(input$files_rows_selected)
      
      df <- all_files()[[
        input$upload$name[[ordre[input$files_rows_selected]]]
      ]]
      plan <<- valider_donnees(plan = plan, input = input, df = df, a_modifier = "champ")
    })
    
    observeEvent(input$chapitre, {
      req(input$upload)
      req(all_files())
      req(input$files_rows_selected)
      
      df <- all_files()[[
        input$upload$name[[ordre[input$files_rows_selected]]]
      ]]
      plan <<- valider_donnees(plan = plan, input = input, df = df, a_modifier = "chapitre")
    })
    
    observeEvent(input$sous_chapitre, {
      req(input$upload)
      req(all_files())
      req(input$files_rows_selected)
      
      df <- all_files()[[
        input$upload$name[[ordre[input$files_rows_selected]]]
      ]]
      plan <<- valider_donnees(plan = plan, input = input, df = df, a_modifier = "sous_chapitre")
    })
    
    proxy_contents <- dataTableProxy("contents")
    proxy_contents_fusion <- dataTableProxy("contents_fusion")
    
    observeEvent(input$validate_colonnes, {
      req(input$upload)
      req(all_files())
      req(input$files_rows_selected)
      
      df <- all_files()[[
        input$upload$name[[ordre[input$files_rows_selected]]]
      ]]
      plan <<- valider_donnees(plan = plan, input = input, df = df, a_modifier = "data_types")
      plan <<- valider_donnees(plan = plan, input = input, df = df, a_modifier = "taille_colonnes")
      widths <- c()
      for (i in 1:ncol(df)) {
        widths <- append(widths, eval(parse(text = paste("input$taille_", as.character(i), sep = ""))))
      }
      if (sum(widths) > 83  & input$format == "chiffres_et_donnees" & isTRUE(input$largeur_max)) {
        shinyalert("La largeur totale dépasse 83", type = "warning")
      } else {
        shinyalert("Modifications enregistrées", type = "success", timer = 1000)
      }
      
    })
    
    observeEvent(input$validate_unites, {
      req(input$upload)
      req(all_files())
      req(input$files_rows_selected)
      
      df <- all_files()[[
        input$upload$name[[ordre[input$files_rows_selected]]]
      ]]
      plan <<- valider_donnees(plan = plan, input = input, df = df, a_modifier = "unites")
      shinyalert("Modifications enregistrées", type = "success", timer = 1000)
    })
    
    observeEvent(input$add_fusion, {
      req(input$upload)
      req(input$files_rows_selected)
      req(input$contents_fusion_cells_selected)
      tab_index <- input$files_rows_selected
      cells <- input$contents_fusion_cells_selected
      min_line <- min(cells[,1])
      max_line <- max(cells[,1])
      min_col <- min(cells[,2])
      max_col <- max(cells[,2])
      current <- plan$Cellules_a_fusionner[tab_index]
      to_add <- paste("(", min_line, ":", max_line, ";", min_col, ":", max_col, ")", sep = "")
      
      if (current == "") {
        plan$Cellules_a_fusionner[tab_index] <<- to_add
      } else {
        new_value <- paste(current, to_add, sep = ", ")
        plan$Cellules_a_fusionner[tab_index] <<- new_value
      }
      output$liste_fusion <- renderPrint(plan$Cellules_a_fusionner[input$files_rows_selected])
      selectCells(proxy_contents_fusion, NULL)
    })
    
    observeEvent(input$files_order_rows_selected, {
      output$liste_ordre <- renderPrint(input$files_order_rows_selected)
    })
    
    observeEvent(input$delete_last_merge, {
      req(input$files_rows_selected)
      liste_fusion <- unlist(strsplit(plan$Cellules_a_fusionner[input$files_rows_selected],
                                      split = ", "))
      char_liste_fusion <- paste(liste_fusion[-length(liste_fusion)], collapse = ", ")
      plan$Cellules_a_fusionner[input$files_rows_selected] <<- char_liste_fusion
      output$liste_fusion <- renderPrint(plan$Cellules_a_fusionner[input$files_rows_selected])
    })
    observeEvent(input$validate_order, {
      req(input$files_order_rows_selected)
      selection <- input$files_order_rows_selected
      if (length(selection) == dim(input$upload)[1]) {
        ordre <<- input$files_order_rows_selected
      
        output$files <- renderDataTable({
          req(input$upload)
          df <- input$upload[ordre,]
          rownames(df) <- 1:nrow(df)
          datatable(df,
                    selection = list(mode = "single", selected = 1))
          })
        
        if (length(input$upload_plan) == 0) {
          plan <<- fill_plan(plan = agreste::modele_plan[NULL,], input = input)
        }
        
        if (is.null(input$upload_plan)[1]) {
          old_index_title <- plan$Titre_document[1]
          plan <<- plan[ordre,]
          rownames(plan) <<- 1:nrow(plan)
          plan$Titre_document <<- rep("", nrow(plan))
          plan$Titre_document[1] <<- old_index_title
        }
        shinyalert("L'ordre a été modifié", type = "success", timer = 750)
      } else {
        shinyalert("Veuillez sélectionner tous les tableaux.", type = "error")
      }
      
    })
    
    output$enreg <- downloadHandler(
      filename = function() {
        "document_formate.xlsx"
      },
      content = function(file) {
        
        col_debut <- switch (input$format,
          "chiffres_et_donnees" = 1,
          "primeur" = 2
        )
        plan[is.na(plan)] <- ""
        is_error <- FALSE
        index_error <- 0
        for (i in 1:dim(plan)[1]) {
          if (plan$Type_colonnes[i] == "" | plan$Liste_unites[i] == "" | plan$Taille_colonnes[i] == "") {
            is_error <- TRUE
            index_error <- i
          }
        }
        if (is_error & length(input$upload_plan) == 0) {
          shinyalert(paste("Veuillez vérifier les colonnes et les unités du tableau", i), type = "error")
        } else {
          shinyalert(title = "Formatage en cours...",
                     text = "Vos tableaux sont en cours de formatage, vous pouvez vous rendre dans la console de RStudio pour suivre l'avancement du traitement. Votre tableau Excel formaté sera téléchargé directement dans votre navigateur.",
                     type = "info",
                     closeOnClickOutside = TRUE,
                     animation = "slide-from-bottom",
                     size = "l")
          
          creer_excel_depuis_plan(plan = plan,
                                  format = input$format,
                                  datadir = datapath,
                                  sep = input$sep,
                                  type_virgule = input$virg,
                                  col_debut = col_debut,
                                  save = TRUE,
                                  path = file,
                                  utiliser_largeur_max = input$largeur_max)
          
        }
      }
    )
  }
  
  shinyApp(ui = ui,
          server = server,
          options = list(launch.browser = TRUE))
}


#' rempli le plan par défaut
#' 
#' @param plan DATA.FRAME le dataframe de plan
#' 
#' @return un data.frame de plan complété
#' @noRd
fill_plan <- function(plan, input) {
  n_tab <- length(input$upload$name)
  lignes <- data.frame(matrix("", n_tab, ncol(plan)))
  names(lignes) <- names(plan)
  plan <- rbind(plan, lignes)
  titre_doc <- "Titre du document"
  plan$Titre_document[1] <- titre_doc
  for (tab_index in 1:n_tab) {
    filename <- input$upload$name[tab_index]
    file_ext <- get.ext(filename)
    nom_fichier <- str_replace(filename,
                               paste(".", file_ext, sep = ""),
                               "")
    nom_feuille <- paste("Feuille", tab_index)
    titre <- paste("Titre tableau", tab_index)
    note <- paste("Note de lecture", tab_index)
    source <- paste("Source", tab_index)
    champ <- paste("Champ", tab_index)
    
    plan$Nom_fichier[tab_index] <- nom_fichier
    plan$Type[tab_index] <- file_ext
    plan$Nom_feuille[tab_index] <- nom_feuille
    plan$Titre[tab_index] <- titre
    plan$Note_de_lecture[tab_index] <- note
    plan$Source[tab_index] <- source
    plan$Champ[tab_index] <- champ
    plan$Lignes_titre[tab_index] <- "1"
  }
  
  return(plan)
}

#' Enregistre les données de l'app vers le plan
#' 
#' @param plan le dataframe de plan
#' @param input les inputs shiny
#' @param df le tableau actuellement sélectionné
#' @param a_modifier CHAR parmi "titre_primeur", "feuille", "titre", 
#' "data_types", "taille_colonnes", "unites", "note", "source", "champ", 
#' "chapitre", "sous_chapitre"
#' 
#' @return le dataframe de plan modifié
#' @noRd
valider_donnees <- function(plan, input, df, a_modifier) {
  
  index_tab <- input$files_rows_selected
  
  vec_data_types <- c()
  vec_col_width <- c()
  vec_unites <- c()
  
  for (i in 1:ncol(df)) {
    id_types <- eval(parse(text = paste("input$col_", as.character(i), sep = "")))
    id_widths <- eval(parse(text = paste("input$taille_", as.character(i), sep = "")))
    char_type <- eval(parse(text = paste("input$unite_", as.character(i), sep = "")))
    if (is.null(char_type)) {
      id_unites <- " "
    } else {
      id_unites <- char_type
    }
    vec_unites <- append(vec_unites, id_unites)
    vec_data_types <- append(vec_data_types, id_types)
    vec_col_width <- append(vec_col_width, id_widths)
  }
  if (a_modifier == "titre_primeur") {
    plan$Titre_document[1] <- input$titre_primeur
  } else if (a_modifier == "feuille") {
    plan$Nom_feuille[index_tab] <- input$feuille
  } else if (a_modifier == "titre") {
    plan$Titre[index_tab] <- input$title
  } else if (a_modifier == "data_types") {
    plan$Type_colonnes[index_tab] <- paste(vec_data_types, collapse = ", ")
  } else if (a_modifier == "taille_colonnes") {
    plan$Taille_colonnes[index_tab] <- paste(vec_col_width, collapse = ", ")
  } else if (a_modifier == "unites") {
    if (input$is_unite_unif == "oui") {
    plan$Liste_unites[index_tab] <- vec_unites[1]
    } else {
    plan$Liste_unites[index_tab] <- paste(vec_unites, collapse = ", ")
    }
  } else if (a_modifier == "note") {
    plan$Note_de_lecture[index_tab] <- input$note
  } else if (a_modifier == "source") {
    plan$Source[index_tab] <- input$source
  } else if (a_modifier == "champ") {
    plan$Champ[index_tab] <- input$champ
  } else if (a_modifier == "chapitre") {
    plan$Chapitre[index_tab] <- input$chapitre
  } else if (a_modifier == "sous_chapitre") {
    plan$`Sous-chapitre`[index_tab] <- input$sous_chapitre
  }
  return(plan)
} 
